[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.10'
optimizer = true
optimizer_runs = 2000
remappings = [
    'core/=src/core/',
    'periphery/=src/periphery',
    'mocks/=src/test/mocks',
    'forge-std/=lib/forge-std/src',
    'rollup-encoder/=lib/rollup-encoder/src',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/', 
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@uniswap/v2-periphery/=lib/v2-periphery/',
    '@uniswap/v2-core/=lib/v2-core/',
    'bridge-deployments/=lib/aztec-connect-bridges/src/deployment',
    'bridge-tests/=lib/aztec-connect-bridges/src/test',
    'bridge-interfaces/=lib/aztec-connect-bridges/src/interfaces'
    ]
fs_permissions = [
    {access = "read", path = 'verification-keys/mock_rollup_proof_data_3x2.dat'},
    {access = "read", path = 'verification-keys/rollup_proof_data_1x1.dat'},
    {access = "read", path = 'verification-keys/encoded_rollup_proof_data_1x1.dat'},
    {access = "write", path = 'serve/contract_addresses.json'},
]

[fmt]
variable_override_spacing=false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config